Add task for setting custom TTL
mulesoft/docs-object-store pull request #51
Opened 2020-09-14 23:16 UTC by hannanelson

2020-09-14 23:21 UTC, podviaznikov reviewed
this looks good to me

2020-09-17 18:49 UTC, schinthakindims requested changes

2020-09-17 18:49 UTC, schinthakindims commented on modules/ROOT/pages/osv2-guide.adoc
> +Otherwise, enter the custom TTL (between 0 and 2592000 seconds).
Should we specifiy that anything > 2592000 will be defaulted to 2592000?

2020-09-17 21:02 UTC, schinthakindims submitted a review, later dismissed

2020-09-17 21:06 UTC, raju-sfdc submitted a review, later dismissed

2020-09-17 22:16 UTC, kbostrom reviewed
Edited per scope of request

2020-09-17 22:16 UTC, kbostrom commented on modules/ROOT/pages/osv2-guide.adoc
> +== Configure a Custom Time-to-Live
Because Time-to-Live is hyphenated here, as a compound adjective, I would give it an object, such as "Value" or, as used below, "Period."
Funny thing is I looked it up, and most uses I saw were unhyphenated....

2020-09-17 22:16 UTC, kbostrom commented on modules/ROOT/pages/osv2-guide.adoc
> +For Object Store v2, the *Max entries* field is not configurable.
I would not follow a graphic with a NOTE with a list.
Consider leaving *Max entries* in the list, in its proper chronological place, and simple define as not configurable.
Also, consider introducing the list with a fragment or sentence, since the intro precedes the graphic.

2020-09-17 22:16 UTC, kbostrom commented on modules/ROOT/pages/osv2-guide.adoc
> +Otherwise, enter the custom TTL (between 0 and 2592000 seconds).
The introduction to this task is how to create a CUSTOM TTL, not how to use rolling TTL, so I would not mention this or, if you feel you must, I would not make it the first sentence. Assumably, the user will NOT be leaving this field empty. It is confusing to include this; outside the scope of the topic.

2020-09-17 22:16 UTC, kbostrom commented on modules/ROOT/pages/osv2-guide.adoc
> +For Mule versions earlier than 4.2.1, leave this field empty to set the TTL to the maximum (2592000 seconds).
Yeah, this further complicates this definition.
If it is technically accurate, I suggest an entry similar to this:

***Entry ttl** 
+
For Mule 4.2.1 and later, enter a custom TTL value of 0 through 2592000 seconds (30 days). If you leave this field empty, you enable rolling TTL; if you exceed 2592000 seconds, the TTL defaults to 2592000 seconds. 
+
For Mule versions earlier than 4.2.1, leaving this field empty defaults to 2592000 seconds.

2020-09-17 22:16 UTC, kbostrom commented on modules/ROOT/pages/osv2-guide.adoc
> +Specify the time interval, such as MINUTES, for the TTL.
```suggestion
Specify the TTL time interval, such as MINUTES.
```

2020-09-17 22:16 UTC, kbostrom commented on modules/ROOT/pages/osv2-guide.adoc
> +Specify the time unit, such as MINUTES, for the expiration interval.
```suggestion
Specify the expiration interval time unit, such as MINUTES.
```

2020-09-17 22:16 UTC, kbostrom commented on modules/ROOT/pages/osv2-guide.adoc
> +. Click *OK* to dismiss the *Global Object Store Configuration* window.
c/b
```suggestion
. Click *OK* to dismiss the window.
```

2020-09-17 22:16 UTC, kbostrom submitted a review, later dismissed
Oops

2020-09-17 22:43 UTC, kbostrom approved these changes
Reapproved (not reedited)

2020-09-21 18:57 UTC, merged